# How to solve this:
# For the first one, you can probably just "do it"
# Beyond that, guess the semantic groups, allowing you to place more than 4 per group
# E.g.
# DETERMINANT DIAGONAL DIMENSION DIRECT_SUM DUAL
# DEDEKIND_CUT DESCENDING_CHAIN DILWORTH DOWN-SET DOMINATION_NUMBER DUALITY_GAP
# DEGENERATE DEGENERACY DENSITY DIAMETER DOMINATION_NUMBER DESCENDING_CHAIN
# DEGENERACY DEGENERATE DESCENT DUAL DUALITY_GAP DIAGONAL
#
# It turns out that usually, there are not that many ways to select a valid guess from these (< 20 if you are reasonable)
# You can then automatically submit all your guesses using https://github.com/Kattis/kattis-cli

first_word = input().split()[0]

if first_word == "DIARY":
    print("""DATE DURIAN DAMSON DRAGONFRUIT
DAY DEADLINE DECEMBER DIARY
DALMATIAN DACHSHUND DOBERMAN DINGO
DARTS DOMINOES DRAUGHTS DODGEBALL""")

elif first_word == "DROP":
    print("""DROP DEREF DEBUG DEFAULT
DEL DICT DIVMOD DIR
DF DU DD DIRNAME
DYNAMIC_CAST DECLTYPE DO DOUBLE""")

elif first_word == "DUAL":
    print("""DIRECT_SUM DIAGONAL DETERMINANT DIMENSION
DILWORTH DEDEKIND_CUT DESCENDING_CHAIN DOWN-SET
DEGENERACY DOMINATION_NUMBER DIAMETER DENSITY
DEGENERATE DUAL DUALITY_GAP DESCENT""")

elif first_word == "DECAY":
    print("""DOPPLER DAMPING DEVIATION DISPERSION
DEFECT DILEMMA DICTATOR DOMINANT
DEVELOPMENT DIMINISHED DRONE DECAY
DESPERADO DECOY DOMINATION DEFLECTION""")

elif first_word == "DITHER":
    print("""DIVIDEND DELTA DISCOUNT DERIVATIVE
DITHER DISTORTION DELAY DECIMATION
DECODER DROPOUT DISTILLATION DENSE
DRAW DEPENDENT DICE DISJOINT""")
